import { Inter } from 'next/font/google'
import VerticalMenu from './components/VerticalMenu';
import MainLayout from './components/MainLayout';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Qr Menü Admin Paneli',
    description: 'Generated by Kreatif Destek',
}

export default function RootLayout({ children }) {
    return (
        <html lang="tr">
            <head>
                <link rel="icon" href="/favicon.ico" sizes="any" />
            </head>
            <body className={inter.className}>
                <VerticalMenu />
                <MainLayout >
                    {children}
                </MainLayout>
            </body>
        </html >
    )
}
